"""empty message

Revision ID: 21390ee5193e
Revises: af978735d6f2
Create Date: 2022-11-26 16:23:12.397306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21390ee5193e'
down_revision = 'af978735d6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'people_id', 'planet_id')
    )
    op.drop_table('Favorite_People')
    op.drop_table('Favorite_Planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorite_Planet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Favorite_Planet_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='Favorite_Planet_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='Favorite_Planet_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Favorite_Planet_pkey'),
    sa.UniqueConstraint('planet_id', name='Favorite_Planet_planet_id_key')
    )
    op.create_table('Favorite_People',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Favorite_People_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='Favorite_People_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='Favorite_People_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Favorite_People_pkey'),
    sa.UniqueConstraint('people_id', name='Favorite_People_people_id_key')
    )
    op.drop_table('Favorites')
    # ### end Alembic commands ###
