"""empty message

Revision ID: b9b28c9dcacf
Revises: dd1d14260a57
Create Date: 2022-11-25 09:25:49.295418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b28c9dcacf'
down_revision = 'dd1d14260a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_constraint('Favorites_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('Favorites_user_id_key', ['user_id'])

    # ### end Alembic commands ###
